### ISSUE TITLE
Development of API for storing external letters

### ISSUE THREAD

**Issue by seonghun-dev** [depromeet/ggogeet_backend#4]
## Explain
Development of API for storing external letters

## Todo
Text Letter
- [x] Create External Letter
- [x] Read External Letter
- [x] Update External Letter
- [x] Delete External Letter

## Test
